services:
  - type: web
    name: currency-converter-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python client.py"
    envVars:
      - key: FLASK_ENV
        value: production
    port: 5000

  - type: background
    name: tcp-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python tcp_server.py"
    port: 5001

  - type: background
    name: udp-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python udp_server.py"
    port: 5002
